[package]
name = "fp_dhcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

colored = "2.0.0"
fern = "0.6.2"
log = "0.4.17"
chrono = "0.4.24"
