[package]
name = "fp_dhcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mac_address = "0"
chrono = "0.4.24"
itertools = "0.10.5"
enum-iterator = "1.4.0"
nohash-hasher = "0.2.0"
log = "0.4.17"
