name: Audit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security_audit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
