name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: cargo-test-x86_64-linux
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --all-features

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features

  miri:
    name: cargo-miri-x86_64-linux
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: miri

      - name: Setup miri
        run: cargo miri setup

      - name: Run miri
        run: cargo miri test --all-features
